server:
  port: 8085

console:
  username: admin
  password: admin123

http:
    request:
        #从连接池中获取到连接的最长时间
        connectionRequestTimeout: 500
        #数据传输的最长时间
        connectTimeout: 2000
        #提交请求前测试连接是否可用
        socketTimeout: 10000
        #提交请求前测试连接是否可用
        staleConnectionCheckEnabled: true

    pool:
       #设置连接总数
       maxTotal: 200
       #设置每个地址的并发数
       defaultMaxPerRoute: 100

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  datasource:
    minIdle: 5
    initialSize: 10
    maxActive: 200
    maxWait: 1000
    useUnfairLock: true

    url: jdbc:mysql://rm-bp1rh20rix7j8eix9125010qm.mysql.rds.aliyuncs.com:3306/advert?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: advert001
    password: ABC!@#abc
    driverClassName: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1
    connectionInitSqls: set names utf8mb4

spring:
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    #prefix=
    request-context-attribute: request
    #settings.*=
    suffix: .ftl
    template-loader-path: classpath:/templates/
    #view-names= # whitelist of view names that can be resolved
    settings:
        template_update_delay: 5
        default_encoding: UTF-8
        locale: UTF-8
        datetime_format: yyyy-MM-dd HH:mm:ss
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        number_format: 0.####
        boolean_format: true,false
        whitespace_stripping: true
        tag_syntax: auto_detect
        url_escaping_charset: UTF-8